### ISSUE TITLE
Map centers on showing a callout view

### ISSUE THREAD

**Issue by jonerickson** [ryanmaxwell/GoogleMapsCalloutView#2]
Every time a annotation is selected and the respective callout is shown, it centers the map on the callout and map annotation. Is there a way to make it stop doing that? I also changed up the way the callout is shown, I added it within didTapMarker and returned NO. It seemed more logical to display the callout from within that method then markerInfoWindow. In markerInfoWindow I am still returning the empty view so that the default is not shown.

**Comment by ryanmaxwell** [comment]
Seems that this is a change in behaviour in the Google Maps iOS SDK. Well, there's a way to [stop it](http://stackoverflow.com/questions/16084944/how-to-change-default-camera-behavior-when-marker-is-tapped) so I've [committed](https://github.com/ryanmaxwell/GoogleMapsCalloutView/commit/bb8e37e2a5f190d48d7911715be3a64b449b5c10) that change. 

There's also a new SDK 1.4, so I'll look at updating this project shortly.

**Comment by jonerickson** [comment]
Which is what I did originally, but the callout view will disappear when panning the map if you return TRUE.

**Comment by ryanmaxwell** [comment]
Check out my code. The markers aren't disappearing

**Comment by jonerickson** [comment]
Woops, didn't realize you had to set the map's selected marker with mapView.selectedMarker = marker; Makes sense now. Thanks. All is working.
